// Extensions and mime types extracted from different sources

// AMD shim
(function(root, factory) {
    if (typeof define === 'function' && define.amd) {
        define(factory);
    } else {
        root.mimeTypeList = factory();
    }
}(this, function() {

    "use strict";

    return {
        "application/envoy": "evy",
        "application/fractals": "fif",
        "application/futuresplash": "spl",
        "application/hta": "hta",
        "application/internet-property-stream": "acx",
        "application/mac-binhex40": "hqx",
        "application/msword": [
            "doc",
            "dot",
            "w6w",
            "wiz",
            "word"
        ],
        "application/octet-stream": [
            "*"
        ],
        "application/oda": "oda",
        "application/olescript": "axs",
        "application/pdf": "pdf",
        "application/pics-rules": "prf",
        "application/pkcs10": "p10",
        "application/pkix-crl": "crl",
        "application/postscript": [
            "ai",
            "eps",
            "ps"
        ],
        "application/rtf": [
            "rtf",
            "rtx"
        ],
        "application/set-payment-initiation": "setpay",
        "application/set-registration-initiation": "setreg",
        "application/vnd.ms-excel": [
            "xla",
            "xlc",
            "xlm",
            "xls",
            "xlt",
            "xlw",
            "xlb",
            "xll"
        ],
        "application/vnd.ms-outlook": "msg",
        "application/vnd.ms-pkicertstore": "sst",
        "application/vnd.ms-pkiseccat": "cat",
        "application/vnd.ms-pkistl": "stl",
        "application/vnd.ms-powerpoint": [
            "pot",
            "pps",
            "ppt",
            "ppa",
            "pwz"
        ],
        "application/vnd.ms-project": "mpp",
        "application/vnd.ms-works": [
            "wcm",
            "wdb",
            "wks",
            "wps"
        ],
        "application/winhlp": "hlp",
        "application/x-bcpio": "bcpio",
        "application/x-cdf": "cdf",
        "application/x-compress": "z",
        "application/x-compressed": [
            "tgz",
            "gz",
            "z",
            "zip"
        ],
        "application/x-cpio": "cpio",
        "application/x-csh": "csh",
        "application/x-director": [
            "dcr",
            "dir",
            "dxr"
        ],
        "application/x-dvi": "dvi",
        "application/x-gtar": "gtar",
        "application/x-gzip": [
            "gz",
            "gzip"
        ],
        "application/x-hdf": "hdf",
        "application/x-internet-signup": [
            "ins",
            "isp"
        ],
        "application/x-iphone": "iii",
        "application/x-javascript": "js",
        "application/x-latex": [
            "latex",
            "ltx"
        ],
        "application/x-msaccess": "mdb",
        "application/x-mscardfile": "crd",
        "application/x-msclip": "clp",
        "application/x-msdownload": [
            "dll",
            "exe"
        ],
        "application/x-msmediaview": [
            "m13",
            "m14",
            "mvb"
        ],
        "application/x-msmetafile": "wmf",
        "application/x-msmoney": "mny",
        "application/x-mspublisher": "pub",
        "application/x-msschedule": "scd",
        "application/x-msterminal": "trm",
        "application/x-mswrite": "wri",
        "application/x-netcdf": [
            "cdf",
            "nc"
        ],
        "application/x-perfmon": [
            "pma",
            "pmc",
            "pml",
            "pmr",
            "pmw"
        ],
        "application/x-pkcs12": [
            "p12",
            "pfx"
        ],
        "application/x-pkcs7-certificates": [
            "p7b",
            "spc"
        ],
        "application/x-pkcs7-certreqresp": "p7r",
        "application/x-pkcs7-mime": [
            "p7c",
            "p7m"
        ],
        "application/x-pkcs7-signature": [
            "p7s",
            "p7a"
        ],
        "application/x-sh": "sh",
        "application/x-shar": [
            "shar",
            "sh"
        ],
        "application/x-shockwave-flash": "swf",
        "application/x-stuffit": "sit",
        "application/x-sv4cpio": "sv4cpio",
        "application/x-sv4crc": "sv4crc",
        "application/x-tar": "tar",
        "application/x-tcl": "tcl",
        "application/x-tex": "tex",
        "application/x-texinfo": [
            "texi",
            "texinfo"
        ],
        "application/x-troff": [
            "roff",
            "t",
            "tr"
        ],
        "application/x-troff-man": "man",
        "application/x-troff-me": "me",
        "application/x-troff-ms": "ms",
        "application/x-ustar": "ustar",
        "application/x-wais-source": [
            "src",
            "wsrc"
        ],
        "application/x-x509-ca-cert": [
            "cer",
            "crt",
            "der"
        ],
        "application/ynd.ms-pkipko": "pko",
        "application/zip": "zip",
        "audio/basic": [
            "au",
            "snd"
        ],
        "audio/mid": [
            "mid",
            "rmi"
        ],
        "audio/mpeg": [
            "mp3",
            "m2a",
            "mp2",
            "mpa",
            "mpg",
            "mpga"
        ],
        "audio/x-aiff": [
            "aif",
            "aifc",
            "aiff"
        ],
        "audio/x-mpegurl": "m3u",
        "audio/x-pn-realaudio": [
            "ra",
            "ram",
            "rm",
            "rmm",
            "rmp"
        ],
        "audio/x-wav": "wav",
        "image/bmp": [
            "bmp",
            "bm"
        ],
        "image/cis-cod": "cod",
        "image/gif": "gif",
        "image/ief": [
            "ief",
            "iefs"
        ],
        "image/jpeg": [
            "jpe",
            "jpeg",
            "jpg",
            "jfif",
            "jfif-tbnl"
        ],
        "image/pipeg": "jfif",
        "image/svg+xml": "svg",
        "image/tiff": [
            "tif",
            "tiff"
        ],
        "image/x-cmu-raster": "ras",
        "image/x-cmx": "cmx",
        "image/x-icon": "ico",
        "image/x-portable-anymap": "pnm",
        "image/x-portable-bitmap": "pbm",
        "image/x-portable-graymap": "pgm",
        "image/x-portable-pixmap": "ppm",
        "image/x-rgb": "rgb",
        "image/x-xbitmap": "xbm",
        "image/x-xpixmap": [
            "xpm",
            "pm"
        ],
        "image/x-xwindowdump": "xwd",
        "message/rfc822": [
            "mht",
            "mhtml",
            "nws",
            "mime",
            "eml"
        ],
        "text/css": "css",
        "text/h323": "323",
        "text/html": [
            "htm",
            "html",
            "stm",
            "acgi",
            "htmls",
            "htx",
            "shtml"
        ],
        "text/iuls": "uls",
        "text/plain": [
            "bas",
            "c",
            "h",
            "txt",
            "c++",
            "cc",
            "com",
            "conf",
            "cxx",
            "def",
            "f",
            "f90",
            "for",
            "g",
            "hh",
            "idc",
            "jav",
            "java",
            "list",
            "log",
            "lst",
            "m",
            "mar",
            "pl",
            "sdml",
            "text"
        ],
        "text/richtext": [
            "rtx",
            "rt",
            "rtf"
        ],
        "text/scriptlet": "sct",
        "text/tab-separated-values": "tsv",
        "text/webviewhtml": "htt",
        "text/x-component": "htc",
        "text/x-setext": "etx",
        "text/x-vcard": "vcf",
        "video/mpeg": [
            "mp2",
            "mpa",
            "mpe",
            "mpeg",
            "mpg",
            "mpv2",
            "m1v",
            "m2v",
            "mp3"
        ],
        "video/quicktime": [
            "mov",
            "qt",
            "moov"
        ],
        "video/x-la-asf": [
            "lsf",
            "lsx"
        ],
        "video/x-ms-asf": [
            "asf",
            "asr",
            "asx"
        ],
        "video/x-msvideo": "avi",
        "video/x-sgi-movie": [
            "movie",
            "mv"
        ],
        "x-world/x-vrml": [
            "flr",
            "vrml",
            "wrl",
            "wrz",
            "xaf",
            "xof"
        ],
        "x-world/x-3dmf": [
            "3dm",
            "3dmf",
            "qd3",
            "qd3d"
        ],
        "application/x-authorware-bin": "aab",
        "application/x-authorware-map": "aam",
        "application/x-authorware-seg": "aas",
        "text/vnd.abc": "abc",
        "video/animaflex": "afl",
        "audio/aiff": [
            "aif",
            "aifc",
            "aiff"
        ],
        "application/x-aim": "aim",
        "text/x-audiosoft-intra": "aip",
        "application/x-navi-animation": "ani",
        "application/x-nokia-9000-communicator-add-on-software": "aos",
        "application/mime": "aps",
        "application/arj": "arj",
        "image/x-jg": "art",
        "text/x-asm": [
            "asm",
            "s"
        ],
        "text/asp": "asp",
        "application/x-mplayer2": "asx",
        "video/x-ms-asf-plugin": "asx",
        "audio/x-au": "au",
        "application/x-troff-msvideo": "avi",
        "video/avi": "avi",
        "video/msvideo": "avi",
        "video/avs-video": "avs",
        "application/mac-binary": "bin",
        "application/macbinary": "bin",
        "application/x-binary": "bin",
        "application/x-macbinary": "bin",
        "image/x-windows-bmp": "bmp",
        "application/book": [
            "boo",
            "book"
        ],
        "application/x-bzip2": [
            "boz",
            "bz2"
        ],
        "application/x-bsh": [
            "bsh",
            "sh",
            "shar"
        ],
        "application/x-bzip": "bz",
        "text/x-c": [
            "c",
            "cc",
            "cpp"
        ],
        "application/vnd.ms-pki.seccat": "cat",
        "application/clariscad": "ccad",
        "application/x-cocoa": "cco",
        "application/cdf": "cdf",
        "application/pkix-cert": [
            "cer",
            "crt"
        ],
        "application/x-chat": [
            "cha",
            "chat"
        ],
        "application/java": "class",
        "application/java-byte-code": "class",
        "application/x-java-class": "class",
        "application/mac-compactpro": "cpt",
        "application/x-compactpro": "cpt",
        "application/x-cpt": "cpt",
        "application/pkcs-crl": "crl",
        "application/x-x509-user-cert": "crt",
        "text/x-script.csh": "csh",
        "application/x-pointplus": "css",
        "application/x-deepv": "deepv",
        "video/x-dv": [
            "dif",
            "dv"
        ],
        "video/dl": "dl",
        "video/x-dl": "dl",
        "application/commonground": "dp",
        "application/drafting": "drw",
        "drawing/x-dwf": "dwf",
        "model/vnd.dwf": "dwf",
        "application/acad": "dwg",
        "image/vnd.dwg": [
            "dwg",
            "dxf",
            "svf"
        ],
        "image/x-dwg": [
            "dwg",
            "dxf",
            "svf"
        ],
        "application/dxf": "dxf",
        "text/x-script.elisp": "el",
        "application/x-bytecode.elisp": "elc",
        "application/x-elc": "elc",
        "application/x-envoy": [
            "env",
            "evy"
        ],
        "application/x-esrehber": "es",
        "text/x-fortran": [
            "f",
            "f77",
            "f90",
            "for"
        ],
        "application/vnd.fdf": "fdf",
        "image/fif": "fif",
        "video/fli": "fli",
        "video/x-fli": "fli",
        "image/florian": [
            "flo",
            "turbot"
        ],
        "text/vnd.fmi.flexstor": "flx",
        "video/x-atomic3d-feature": "fmf",
        "image/vnd.fpx": "fpx",
        "image/vnd.net-fpx": [
            "fpx",
            "npx"
        ],
        "application/freeloader": "frl",
        "audio/make": [
            "funk",
            "my",
            "pfunk"
        ],
        "image/g3fax": "g3",
        "video/gl": "gl",
        "video/x-gl": "gl",
        "audio/x-gsm": [
            "gsd",
            "gsm"
        ],
        "application/x-gsp": "gsp",
        "application/x-gss": "gss",
        "multipart/x-gzip": "gzip",
        "text/x-h": [
            "h",
            "hh"
        ],
        "application/x-helpfile": [
            "help",
            "hlp"
        ],
        "application/vnd.hp-hpgl": [
            "hgl",
            "hpg",
            "hpgl"
        ],
        "text/x-script": "hlb",
        "application/hlp": "hlp",
        "application/x-winhelp": "hlp",
        "application/binhex": "hqx",
        "application/binhex4": "hqx",
        "application/mac-binhex": "hqx",
        "application/x-binhex40": "hqx",
        "application/x-mac-binhex40": "hqx",
        "x-conference/x-cooltalk": "ice",
        "application/iges": [
            "iges",
            "igs"
        ],
        "model/iges": [
            "iges",
            "igs"
        ],
        "application/x-ima": "ima",
        "application/x-httpd-imap": "imap",
        "application/inf": "inf",
        "application/x-internett-signup": "ins",
        "application/x-ip2": "ip",
        "video/x-isvideo": "isu",
        "audio/it": "it",
        "application/x-inventor": "iv",
        "i-world/i-vrml": "ivr",
        "application/x-livescreen": "ivy",
        "audio/x-jam": "jam",
        "text/x-java-source": [
            "jav",
            "java"
        ],
        "application/x-java-commerce": "jcm",
        "image/pjpeg": [
            "jfif",
            "jpe",
            "jpeg",
            "jpg"
        ],
        "image/x-jps": "jps",
        "application/javascript": "js",
        "application/ecmascript": [
            "js",
            "es"
        ],
        "text/javascript": "js",
        "text/ecmascript": "js",
        "image/jutvision": "jut",
        "audio/midi": [
            "kar",
            "mid",
            "midi"
        ],
        "music/x-karaoke": "kar",
        "application/x-ksh": "ksh",
        "text/x-script.ksh": "ksh",
        "audio/nspaudio": [
            "la",
            "lma"
        ],
        "audio/x-nspaudio": [
            "la",
            "lma"
        ],
        "audio/x-liveaudio": "lam",
        "application/lha": "lha",
        "application/x-lha": "lha",
        "application/x-lisp": "lsp",
        "text/x-script.lisp": "lsp",
        "text/x-la-asf": "lsx",
        "application/x-lzh": "lzh",
        "application/lzx": "lzx",
        "application/x-lzx": "lzx",
        "text/x-m": "m",
        "audio/x-mpequrl": "m3u",
        "application/x-navimap": "map",
        "application/mbedlet": "mbd",
        "application/x-magic-cap-package-1.0": "mc$",
        "application/mcad": "mcd",
        "application/x-mathcad": "mcd",
        "image/vasa": "mcf",
        "text/mcf": "mcf",
        "application/netmc": "mcp",
        "application/x-midi": [
            "mid",
            "midi"
        ],
        "audio/x-mid": [
            "mid",
            "midi"
        ],
        "audio/x-midi": [
            "mid",
            "midi"
        ],
        "music/crescendo": [
            "mid",
            "midi"
        ],
        "x-music/x-midi": [
            "mid",
            "midi"
        ],
        "application/x-frame": "mif",
        "application/x-mif": "mif",
        "www/mime": "mime",
        "audio/x-vnd.audioexplosion.mjuicemediafile": "mjf",
        "video/x-motion-jpeg": "mjpg",
        "application/base64": [
            "mm",
            "mme"
        ],
        "application/x-meme": "mm",
        "audio/mod": "mod",
        "audio/x-mod": "mod",
        "audio/x-mpeg": "mp2",
        "video/x-mpeg": [
            "mp2",
            "mp3"
        ],
        "video/x-mpeq2a": "mp2",
        "audio/mpeg3": "mp3",
        "audio/x-mpeg-3": "mp3",
        "application/x-project": [
            "mpc",
            "mpt",
            "mpv",
            "mpx"
        ],
        "application/marc": "mrc",
        "application/x-vnd.audioexplosion.mzz": "mzz",
        "image/naplps": [
            "nap",
            "naplps"
        ],
        "application/vnd.nokia.configuration-message": "ncm",
        "image/x-niff": [
            "nif",
            "niff"
        ],
        "application/x-mix-transfer": "nix",
        "application/x-conference": "nsc",
        "application/x-navidoc": "nvd",
        "application/x-omc": "omc",
        "application/x-omcdatamaker": "omcd",
        "application/x-omcregerator": "omcr",
        "text/x-pascal": "p",
        "application/x-pkcs10": "p10",
        "application/pkcs-12": "p12",
        "application/pkcs7-mime": [
            "p7c",
            "p7m"
        ],
        "application/pkcs7-signature": "p7s",
        "application/pro_eng": [
            "part",
            "prt"
        ],
        "text/pascal": "pas",
        "application/vnd.hp-pcl": "pcl",
        "application/x-pcl": "pcl",
        "image/x-pict": [
            "pct",
            "pic"
        ],
        "image/x-pcx": "pcx",
        "chemical/x-pdb": [
            "pdb",
            "xyz"
        ],
        "audio/make.my.funk": "pfunk",
        "image/x-portable-greymap": "pgm",
        "image/pict": [
            "pic",
            "pict"
        ],
        "application/x-newton-compatible-pkg": "pkg",
        "application/vnd.ms-pki.pko": "pko",
        "text/x-script.perl": "pl",
        "application/x-pixclscript": "plx",
        "text/x-script.perl-module": "pm",
        "application/x-pagemaker": [
            "pm4",
            "pm5"
        ],
        "image/png": [
            "png",
            "x-png"
        ],
        "application/x-portable-anymap": "pnm",
        "application/mspowerpoint": [
            "pot",
            "pps",
            "ppt",
            "ppz"
        ],
        "model/x-pov": "pov",
        "application/powerpoint": "ppt",
        "application/x-mspowerpoint": "ppt",
        "application/x-freelance": "pre",
        "paleovu/x-pv": "pvu",
        "text/x-script.phyton": "py",
        "applicaiton/x-bytecode.python": "pyc",
        "audio/vnd.qcelp": "qcp",
        "image/x-quicktime": [
            "qif",
            "qti",
            "qtif"
        ],
        "video/x-qtc": "qtc",
        "audio/x-pn-realaudio-plugin": [
            "ra",
            "rmp",
            "rpm"
        ],
        "audio/x-realaudio": "ra",
        "application/x-cmu-raster": "ras",
        "image/cmu-raster": [
            "ras",
            "rast"
        ],
        "text/x-script.rexx": "rexx",
        "image/vnd.rn-realflash": "rf",
        "application/vnd.rn-realmedia": "rm",
        "application/ringing-tones": "rng",
        "application/vnd.nokia.ringing-tone": "rng",
        "application/vnd.rn-realplayer": "rnx",
        "image/vnd.rn-realpix": "rp",
        "text/vnd.rn-realtext": "rt",
        "application/x-rtf": "rtf",
        "video/vnd.rn-realvideo": "rv",
        "audio/s3m": "s3m",
        "application/x-tbook": [
            "sbk",
            "tbk"
        ],
        "application/x-lotusscreencam": "scm",
        "text/x-script.guile": "scm",
        "text/x-script.scheme": "scm",
        "video/x-scm": "scm",
        "application/sdp": "sdp",
        "application/x-sdp": "sdp",
        "application/sounder": "sdr",
        "application/sea": "sea",
        "application/x-sea": "sea",
        "application/set": "set",
        "text/sgml": [
            "sgm",
            "sgml"
        ],
        "text/x-sgml": [
            "sgm",
            "sgml"
        ],
        "text/x-script.sh": "sh",
        "text/x-server-parsed-html": [
            "shtml",
            "ssi"
        ],
        "audio/x-psid": "sid",
        "application/x-sit": "sit",
        "application/x-koan": [
            "skd",
            "skm",
            "skp",
            "skt"
        ],
        "application/x-seelogo": "sl",
        "application/smil": [
            "smi",
            "smil"
        ],
        "audio/x-adpcm": "snd",
        "application/solids": "sol",
        "text/x-speech": [
            "spc",
            "talk"
        ],
        "application/x-sprite": [
            "spr",
            "sprite"
        ],
        "application/streamingmedia": "ssm",
        "application/vnd.ms-pki.certstore": "sst",
        "application/step": [
            "step",
            "stp"
        ],
        "application/sla": "stl",
        "application/vnd.ms-pki.stl": "stl",
        "application/x-navistyle": "stl",
        "application/x-world": [
            "svr",
            "wrl"
        ],
        "x-world/x-svr": "svr",
        "application/toolbook": "tbk",
        "text/x-script.tcl": "tcl",
        "text/x-script.tcsh": "tcsh",
        "application/plain": "text",
        "application/gnutar": "tgz",
        "image/x-tiff": [
            "tif",
            "tiff"
        ],
        "audio/tsp-audio": "tsi",
        "application/dsptype": "tsp",
        "audio/tsplayer": "tsp",
        "text/x-uil": "uil",
        "text/uri-list": [
            "uni",
            "unis",
            "uri",
            "uris"
        ],
        "application/i-deas": "unv",
        "multipart/x-ustar": "ustar",
        "text/x-uuencode": [
            "uu",
            "uue"
        ],
        "application/x-cdlink": "vcd",
        "text/x-vcalendar": "vcs",
        "application/vda": "vda",
        "video/vdo": "vdo",
        "application/groupwise": "vew",
        "video/vivo": [
            "viv",
            "vivo"
        ],
        "video/vnd.vivo": [
            "viv",
            "vivo"
        ],
        "application/vocaltec-media-desc": "vmd",
        "application/vocaltec-media-file": "vmf",
        "audio/voc": "voc",
        "audio/x-voc": "voc",
        "video/vosaic": "vos",
        "audio/voxware": "vox",
        "audio/x-twinvq-plugin": [
            "vqe",
            "vql"
        ],
        "audio/x-twinvq": "vqf",
        "application/x-vrml": "vrml",
        "model/vrml": [
            "vrml",
            "wrl",
            "wrz"
        ],
        "x-world/x-vrt": "vrt",
        "application/x-visio": [
            "vsd",
            "vst",
            "vsw"
        ],
        "application/wordperfect6.0": [
            "w60",
            "wp5"
        ],
        "application/wordperfect6.1": "w61",
        "audio/wav": "wav",
        "application/x-qpro": "wb1",
        "image/vnd.wap.wbmp": "wbmp",
        "application/vnd.xara": [
            "web",
            "xar"
        ],
        "application/x-123": "wk1",
        "windows/metafile": "wmf",
        "text/vnd.wap.wml": "wml",
        "application/vnd.wap.wmlc": "wmlc",
        "text/vnd.wap.wmlscript": "wmls",
        "application/vnd.wap.wmlscriptc": "wmlsc",
        "application/wordperfect": [
            "wp",
            "wp5",
            "wp6",
            "wpd"
        ],
        "application/x-wpwin": "wpd",
        "application/x-lotus": "wq1",
        "application/mswrite": "wri",
        "application/x-wri": "wri",
        "text/scriplet": "wsc",
        "application/x-wintalk": "wtk",
        "image/x-xbm": "xbm",
        "image/xbm": "xbm",
        "video/x-amt-demorun": "xdr",
        "xgl/drawing": "xgz",
        "image/vnd.xiff": "xif",
        "application/excel": [
            "xl",
            "xla",
            "xlb",
            "xlc",
            "xld",
            "xlk",
            "xll",
            "xlm",
            "xls",
            "xlt",
            "xlv",
            "xlw"
        ],
        "application/x-excel": [
            "xla",
            "xlb",
            "xlc",
            "xld",
            "xlk",
            "xll",
            "xlm",
            "xls",
            "xlt",
            "xlv",
            "xlw"
        ],
        "application/x-msexcel": [
            "xla",
            "xls",
            "xlw"
        ],
        "audio/xm": "xm",
        "application/xml": "xml",
        "text/xml": "xml",
        "xgl/movie": "xmz",
        "application/x-vnd.ls-xpix": "xpix",
        "image/xpm": "xpm",
        "video/x-amt-showrun": "xsr",
        "image/x-xwd": "xwd",
        "application/x-zip-compressed": "zip",
        "multipart/x-zip": "zip",
        "text/x-script.zsh": "zsh",
        "application/vnd.hzn-3d-crossword": "x3d",
        "video/3gpp": "3gp",
        "video/3gpp2": "3g2",
        "application/vnd.mseq": "mseq",
        "application/vnd.3m.post-it-notes": "pwn",
        "application/vnd.3gpp.pic-bw-large": "plb",
        "application/vnd.3gpp.pic-bw-small": "psb",
        "application/vnd.3gpp.pic-bw-var": "pvb",
        "application/vnd.3gpp2.tcap": "tcap",
        "application/x-7z-compressed": "7z",
        "application/x-abiword": "abw",
        "application/x-ace-compressed": "ace",
        "application/vnd.americandynamics.acc": "acc",
        "application/vnd.acucobol": "acu",
        "application/vnd.acucorp": "atc",
        "audio/adpcm": "adp",
        "application/vnd.adobe.air-application-installer-package+zip": "air",
        "application/vnd.adobe.fxp": "fxp",
        "application/vnd.cups-ppd": "ppd",
        "application/vnd.adobe.xdp+xml": "xdp",
        "application/vnd.adobe.xfdf": "xfdf",
        "audio/x-aac": "aac",
        "application/vnd.ahead.space": "ahead",
        "application/vnd.airzip.filesecure.azf": "azf",
        "application/vnd.airzip.filesecure.azs": "azs",
        "application/vnd.amazon.ebook": "azw",
        "application/vnd.amiga.ami": "ami",
        "application/andrew-inset": "",
        "application/vnd.android.package-archive": "apk",
        "application/vnd.anser-web-certificate-issue-initiation": "cii",
        "application/vnd.anser-web-funds-transfer-initiation": "fti",
        "application/vnd.antix.game-component": "atx",
        "application/vnd.apple.installer+xml": "mpkg",
        "application/applixware": "aw",
        "application/vnd.hhe.lesson-player": "les",
        "application/vnd.aristanetworks.swi": "swi",
        "application/atomcat+xml": "atomcat",
        "application/atomsvc+xml": "atomsvc",
        "application/atom+xml": "xml",
        "application/pkix-attr-cert": "ac",
        "application/vnd.audiograph": "aep",
        "image/vnd.dxf": "dxf",
        "text/plain-bas": "par",
        "application/x-bittorrent": "torrent",
        "application/vnd.rim.cod": "cod",
        "application/vnd.blueice.multipass": "mpm",
        "application/vnd.bmi": "bmi",
        "image/prs.btif": "btif",
        "application/vnd.businessobjects": "rep",
        "application/vnd.chemdraw+xml": "cdxml",
        "chemical/x-cdx": "cdx",
        "chemical/x-cml": "cml",
        "chemical/x-csml": "csml",
        "application/vnd.contact.cmsg": "cdbcmsg",
        "application/vnd.claymore": "cla",
        "application/vnd.clonk.c4group": "c4g",
        "image/vnd.dvb.subtitle": "sub",
        "application/cdmi-capability": "cdmia",
        "application/cdmi-container": "cdmic",
        "application/cdmi-domain": "cdmid",
        "application/cdmi-object": "cdmio",
        "application/cdmi-queue": "cdmiq",
        "application/vnd.cluetrust.cartomobile-config": "c11amc",
        "application/vnd.cluetrust.cartomobile-config-pkg": "c11amz",
        "model/vnd.collada+xml": "dae",
        "text/csv": "csv",
        "image/cgm": "cgm",
        "application/vnd.cosmocaller": "cmc",
        "application/vnd.crick.clicker": "clkx",
        "application/vnd.crick.clicker.keyboard": "clkk",
        "application/vnd.crick.clicker.palette": "clkp",
        "application/vnd.crick.clicker.template": "clkt",
        "application/vnd.crick.clicker.wordbank": "clkw",
        "application/vnd.criticaltools.wbs+xml": "wbs",
        "application/vnd.rig.cryptonote": "cryptonote",
        "chemical/x-cif": "cif",
        "chemical/x-cmdf": "cmdf",
        "application/cu-seeme": "cu",
        "application/prs.cww": "cww",
        "text/vnd.curl": "curl",
        "text/vnd.curl.dcurl": "dcurl",
        "text/vnd.curl.mcurl": "mcurl",
        "text/vnd.curl.scurl": "scurl",
        "application/vnd.curl.car": "car",
        "application/vnd.curl.pcurl": "pcurl",
        "application/vnd.yellowriver-custom-menu": "cmp",
        "application/dssc+der": "dssc",
        "application/dssc+xml": "xdssc",
        "application/x-debian-package": "deb",
        "audio/vnd.dece.audio": "uva",
        "image/vnd.dece.graphic": "uvi",
        "video/vnd.dece.hd": "uvh",
        "video/vnd.dece.mobile": "uvm",
        "video/vnd.uvvu.mp4": "uvu",
        "video/vnd.dece.pd": "uvp",
        "video/vnd.dece.sd": "uvs",
        "video/vnd.dece.video": "uvv",
        "application/vnd.fdsn.seed": "seed",
        "application/x-dtbook+xml": "dtb",
        "application/x-dtbresource+xml": "res",
        "application/vnd.dvb.ait": "ait",
        "application/vnd.dvb.service": "svc",
        "audio/vnd.digital-winds": "eol",
        "image/vnd.djvu": "djvu",
        "application/xml-dtd": "dtd",
        "application/vnd.dolby.mlp": "mlp",
        "application/x-doom": "wad",
        "application/vnd.dpgraph": "dpg",
        "audio/vnd.dra": "dra",
        "application/vnd.dreamfactory": "dfac",
        "audio/vnd.dts": "dts",
        "audio/vnd.dts.hd": "dtshd",
        "application/vnd.dynageo": "geo",
        "application/vnd.ecowin.chart": "mag",
        "image/vnd.fujixerox.edmics-mmr": "mmr",
        "image/vnd.fujixerox.edmics-rlc": "rlc",
        "application/exi": "exi",
        "application/vnd.proteus.magazine": "mgz",
        "application/epub+zip": "epub",
        "application/vnd.enliven": "nml",
        "application/vnd.is-xpr": "xpr",
        "application/vnd.xfdl": "xfdl",
        "application/emma+xml": "emma",
        "application/vnd.ezpix-album": "ez2",
        "application/vnd.ezpix-package": "ez3",
        "image/vnd.fst": "fst",
        "video/vnd.fvt": "fvt",
        "image/vnd.fastbidsheet": "fbs",
        "application/vnd.denovo.fcselayout-link": "fe_launch",
        "video/x-f4v": "f4v",
        "video/x-flv": "flv",
        "application/vnd.fluxtime.clip": "ftc",
        "application/vnd.mif": "mif",
        "application/vnd.framemaker": "fm",
        "image/x-freehand": "fh",
        "application/vnd.fsc.weblaunch": "fsc",
        "application/vnd.frogans.fnc": "fnc",
        "application/vnd.frogans.ltf": "ltf",
        "application/vnd.fujixerox.ddd": "ddd",
        "application/vnd.fujixerox.docuworks": "xdw",
        "application/vnd.fujixerox.docuworks.binder": "xbd",
        "application/vnd.fujitsu.oasys": "oas",
        "application/vnd.fujitsu.oasys2": "oa2",
        "application/vnd.fujitsu.oasys3": "oa3",
        "application/vnd.fujitsu.oasysgp": "fg5",
        "application/vnd.fujitsu.oasysprs": "bh2",
        "application/x-futuresplash": "spl",
        "application/vnd.fuzzysheet": "fzs",
        "application/vnd.gmx": "gmx",
        "model/vnd.gtw": "gtw",
        "application/vnd.genomatix.tuxedo": "txd",
        "application/vnd.geogebra.file": "ggb",
        "application/vnd.geogebra.tool": "ggt",
        "model/vnd.gdl": "gdl",
        "application/vnd.geometry-explorer": "gex",
        "application/vnd.geonext": "gxt",
        "application/vnd.geoplan": "g2w",
        "application/vnd.geospace": "g3w",
        "application/x-font-ghostscript": "gsf",
        "application/x-font-bdf": "bdf",
        "application/x-gnumeric": "gnumeric",
        "application/vnd.google-earth.kml+xml": "kml",
        "application/vnd.google-earth.kmz": "kmz",
        "application/vnd.grafeq": "gqf",
        "text/vnd.graphviz": "gv",
        "application/vnd.groove-account": "gac",
        "application/vnd.groove-help": "ghf",
        "application/vnd.groove-identity-message": "gim",
        "application/vnd.groove-injector": "grv",
        "application/vnd.groove-tool-message": "gtm",
        "application/vnd.groove-tool-template": "tpl",
        "application/vnd.groove-vcard": "vcg",
        "video/h261": "h261",
        "video/h263": "h263",
        "video/h264": "h264",
        "application/vnd.hp-hpid": "hpid",
        "application/vnd.hp-hps": "hps",
        "audio/vnd.rip": "rip",
        "application/vnd.hbci": "hbci",
        "application/vnd.hp-jlyt": "jlt",
        "application/vnd.yamaha.hv-script": "hvs",
        "application/vnd.yamaha.hv-dic": "hvd",
        "application/vnd.yamaha.hv-voice": "hvp",
        "application/vnd.hydrostatix.sof-data": "sfd-hdstx",
        "application/hyperstudio": "stk",
        "application/vnd.hal+xml": "hal",
        "application/vnd.ibm.rights-management": "irm",
        "application/vnd.ibm.secure-container": "sc",
        "text/calendar": "ics",
        "application/vnd.iccprofile": "icc",
        "application/vnd.igloader": "igl",
        "application/vnd.immervision-ivp": "ivp",
        "application/vnd.immervision-ivu": "ivu",
        "application/reginfo+xml": "rif",
        "text/vnd.in3d.3dml": "3dml",
        "text/vnd.in3d.spot": "spot",
        "application/vnd.intergeo": "i2g",
        "application/vnd.cinderella": "cdy",
        "application/vnd.intercon.formnet": "xpw",
        "application/vnd.isac.fcs": "fcs",
        "application/ipfix": "ipfix",
        "application/pkixcmp": "pki",
        "application/pkix-pkipath": "pkipath",
        "application/vnd.insors.igm": "igm",
        "application/vnd.ipunplugged.rcprofile": "rcprofile",
        "application/vnd.irepository.package+xml": "irp",
        "text/vnd.sun.j2me.app-descriptor": "jad",
        "application/java-archive": "jar",
        "application/java-vm": "class",
        "application/x-java-jnlp-file": "jnlp",
        "application/java-serialized-object": "ser",
        "text/x-java-source,java": "java",
        "application/json": "json",
        "application/vnd.joost.joda-archive": "joda",
        "video/jpm": "jpm",
        "video/jpeg": "jpgv",
        "application/vnd.kahootz": "ktz",
        "application/vnd.chipnuts.karaoke-mmd": "mmd",
        "application/vnd.kde.karbon": "karbon",
        "application/vnd.kde.kchart": "chrt",
        "application/vnd.kde.kformula": "kfo",
        "application/vnd.kde.kivio": "flw",
        "application/vnd.kde.kontour": "kon",
        "application/vnd.kde.kpresenter": "kpr",
        "application/vnd.kde.kspread": "ksp",
        "application/vnd.kde.kword": "kwd",
        "application/vnd.kenameaapp": "htke",
        "application/vnd.kidspiration": "kia",
        "application/vnd.kinar": "kne",
        "application/vnd.kodak-descriptor": "sse",
        "application/vnd.las.las+xml": "lasxml",
        "application/vnd.llamagraphics.life-balance.desktop": "lbd",
        "application/vnd.llamagraphics.life-balance.exchange+xml": "lbe",
        "application/vnd.jam": "jam",
        "application/vnd.lotus-1-2-3": "123",
        "application/vnd.lotus-approach": "apr",
        "application/vnd.lotus-freelance": "pre",
        "application/vnd.lotus-notes": "nsf",
        "application/vnd.lotus-organizer": "org",
        "application/vnd.lotus-screencam": "scm",
        "application/vnd.lotus-wordpro": "lwp",
        "audio/vnd.lucent.voice": "lvp",
        "video/x-m4v": "m4v",
        "application/vnd.macports.portpkg": "portpkg",
        "application/vnd.osgeo.mapguide.package": "mgp",
        "application/marcxml+xml": "mrcx",
        "application/mxf": "mxf",
        "application/vnd.wolfram.player": "nbp",
        "application/mathematica": "ma",
        "application/mathml+xml": "mathml",
        "application/mbox": "mbox",
        "application/vnd.medcalcdata": "mc1",
        "application/mediaservercontrol+xml": "mscml",
        "application/vnd.mediastation.cdkey": "cdkey",
        "application/vnd.mfer": "mwf",
        "application/vnd.mfmp": "mfm",
        "model/mesh": "msh",
        "application/mads+xml": "mads",
        "application/mets+xml": "mets",
        "application/mods+xml": "mods",
        "application/metalink4+xml": "meta4",
        "application/vnd.ms-powerpoint.template.macroenabled.12": "potm",
        "application/vnd.ms-word.document.macroenabled.12": "docm",
        "application/vnd.ms-word.template.macroenabled.12": "dotm",
        "application/vnd.mcd": "mcd",
        "application/vnd.micrografx.flo": "flo",
        "application/vnd.micrografx.igx": "igx",
        "application/vnd.eszigno3+xml": "es3",
        "application/vnd.ms-artgalry": "cil",
        "application/vnd.ms-cab-compressed": "cab",
        "application/vnd.ms-ims": "ims",
        "application/x-ms-application": "application",
        "image/vnd.ms-modi": "mdi",
        "application/vnd.ms-fontobject": "eot",
        "application/vnd.ms-excel.addin.macroenabled.12": "xlam",
        "application/vnd.ms-excel.sheet.binary.macroenabled.12": "xlsb",
        "application/vnd.ms-excel.template.macroenabled.12": "xltm",
        "application/vnd.ms-excel.sheet.macroenabled.12": "xlsm",
        "application/vnd.ms-htmlhelp": "chm",
        "application/vnd.ms-lrm": "lrm",
        "application/vnd.openxmlformats-officedocument.presentationml.presentation": "pptx",
        "application/vnd.openxmlformats-officedocument.presentationml.slide": "sldx",
        "application/vnd.openxmlformats-officedocument.presentationml.slideshow": "ppsx",
        "application/vnd.openxmlformats-officedocument.presentationml.template": "potx",
        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": "xlsx",
        "application/vnd.openxmlformats-officedocument.spreadsheetml.template": "xltx",
        "application/vnd.openxmlformats-officedocument.wordprocessingml.document": "docx",
        "application/vnd.openxmlformats-officedocument.wordprocessingml.template": "dotx",
        "application/x-msbinder": "obd",
        "application/vnd.ms-officetheme": "thmx",
        "application/onenote": "onetoc",
        "audio/vnd.ms-playready.media.pya": "pya",
        "video/vnd.ms-playready.media.pyv": "pyv",
        "application/vnd.ms-powerpoint.addin.macroenabled.12": "ppam",
        "application/vnd.ms-powerpoint.slide.macroenabled.12": "sldm",
        "application/vnd.ms-powerpoint.presentation.macroenabled.12": "pptm",
        "application/vnd.ms-powerpoint.slideshow.macroenabled.12": "ppsm",
        "application/x-silverlight-app": "xap",
        "application/vnd.visio": "vsd",
        "video/x-ms-wm": "wm",
        "audio/x-ms-wma": "wma",
        "audio/x-ms-wax": "wax",
        "video/x-ms-wmx": "wmx",
        "application/x-ms-wmd": "wmd",
        "application/vnd.ms-wpl": "wpl",
        "application/x-ms-wmz": "wmz",
        "video/x-ms-wmv": "wmv",
        "video/x-ms-wvx": "wvx",
        "application/x-ms-xbap": "xbap",
        "application/vnd.ms-xpsdocument": "xps",
        "application/vnd.ibm.minipay": "mpy",
        "application/vnd.ibm.modcap": "afp",
        "application/vnd.jcp.javame.midlet-rms": "rms",
        "application/vnd.tmobile-livetv": "tmo",
        "application/x-mobipocket-ebook": "prc",
        "application/vnd.mobius.mbk": "mbk",
        "application/vnd.mobius.dis": "dis",
        "application/vnd.mobius.plc": "plc",
        "application/vnd.mobius.mqy": "mqy",
        "application/vnd.mobius.msl": "msl",
        "application/vnd.mobius.txf": "txf",
        "application/vnd.mobius.daf": "daf",
        "text/vnd.fly": "fly",
        "application/vnd.mophun.certificate": "mpc",
        "application/vnd.mophun.application": "mpn",
        "video/mj2": "mj2",
        "video/vnd.mpegurl": "mxu",
        "application/mp21": "m21",
        "audio/mp4": "mp4a",
        "video/mp4": "mp4",
        "application/mp4": "mp4",
        "application/vnd.apple.mpegurl": "m3u8",
        "application/vnd.musician": "mus",
        "application/vnd.muvee.style": "msty",
        "application/xv+xml": "mxml",
        "application/vnd.nokia.n-gage.data": "ngdat",
        "application/vnd.nokia.n-gage.symbian.install": "n-gage",
        "application/x-dtbncx+xml": "ncx",
        "application/vnd.neurolanguage.nlu": "nlu",
        "application/vnd.dna": "dna",
        "application/vnd.noblenet-directory": "nnd",
        "application/vnd.noblenet-sealer": "nns",
        "application/vnd.noblenet-web": "nnw",
        "application/vnd.nokia.radio-preset": "rpst",
        "application/vnd.nokia.radio-presets": "rpss",
        "text/n3": "n3",
        "application/vnd.novadigm.edm": "edm",
        "application/vnd.novadigm.edx": "edx",
        "application/vnd.novadigm.ext": "ext",
        "application/vnd.flographit": "gph",
        "audio/vnd.nuera.ecelp4800": "ecelp4800",
        "audio/vnd.nuera.ecelp7470": "ecelp7470",
        "audio/vnd.nuera.ecelp9600": "ecelp9600",
        "application/ogg": "ogx",
        "audio/ogg": "oga",
        "video/ogg": "ogv",
        "application/vnd.oma.dd2+xml": "dd2",
        "application/vnd.oasis.opendocument.text-web": "oth",
        "application/oebps-package+xml": "opf",
        "application/vnd.intu.qbo": "qbo",
        "application/vnd.openofficeorg.extension": "oxt",
        "application/vnd.yamaha.openscoreformat": "osf",
        "audio/webm": "weba",
        "video/webm": "webm",
        "application/vnd.oasis.opendocument.chart": "odc",
        "application/vnd.oasis.opendocument.chart-template": "otc",
        "application/vnd.oasis.opendocument.database": "odb",
        "application/vnd.oasis.opendocument.formula": "odf",
        "application/vnd.oasis.opendocument.formula-template": "odft",
        "application/vnd.oasis.opendocument.graphics": "odg",
        "application/vnd.oasis.opendocument.graphics-template": "otg",
        "application/vnd.oasis.opendocument.image": "odi",
        "application/vnd.oasis.opendocument.image-template": "oti",
        "application/vnd.oasis.opendocument.presentation": "odp",
        "application/vnd.oasis.opendocument.presentation-template": "otp",
        "application/vnd.oasis.opendocument.spreadsheet": "ods",
        "application/vnd.oasis.opendocument.spreadsheet-template": "ots",
        "application/vnd.oasis.opendocument.text": "odt",
        "application/vnd.oasis.opendocument.text-master": "odm",
        "application/vnd.oasis.opendocument.text-template": "ott",
        "image/ktx": "ktx",
        "application/vnd.sun.xml.calc": "sxc",
        "application/vnd.sun.xml.calc.template": "stc",
        "application/vnd.sun.xml.draw": "sxd",
        "application/vnd.sun.xml.draw.template": "std",
        "application/vnd.sun.xml.impress": "sxi",
        "application/vnd.sun.xml.impress.template": "sti",
        "application/vnd.sun.xml.math": "sxm",
        "application/vnd.sun.xml.writer": "sxw",
        "application/vnd.sun.xml.writer.global": "sxg",
        "application/vnd.sun.xml.writer.template": "stw",
        "application/x-font-otf": "otf",
        "application/vnd.yamaha.openscoreformat.osfpvg+xml": "osfpvg",
        "application/vnd.osgi.dp": "dp",
        "application/vnd.palm": "pdb",
        "application/vnd.pawaafile": "paw",
        "application/vnd.hp-pclxl": "pclxl",
        "application/vnd.picsel": "efif",
        "image/vnd.adobe.photoshop": "psd",
        "application/pkcs8": "p8",
        "application/vnd.pocketlearn": "plf",
        "application/x-font-pcf": "pcf",
        "application/font-tdpfr": "pfr",
        "application/x-chess-pgn": "pgn",
        "application/pskc+xml": "pskcxml",
        "application/vnd.ctc-posml": "pml",
        "application/x-font-type1": "pfa",
        "application/vnd.powerbuilder6": "pbd",
        "application/pgp-encrypted": "",
        "application/pgp-signature": "pgp",
        "application/vnd.previewsystems.box": "box",
        "application/vnd.pvi.ptid1": "ptid",
        "application/pls+xml": "pls",
        "application/vnd.pg.format": "str",
        "application/vnd.pg.osasli": "ei6",
        "text/prs.lines.tag": "dsc",
        "application/x-font-linux-psf": "psf",
        "application/vnd.publishare-delta-tree": "qps",
        "application/vnd.pmi.widget": "wg",
        "application/vnd.quark.quarkxpress": "qxd",
        "application/vnd.epson.esf": "esf",
        "application/vnd.epson.msf": "msf",
        "application/vnd.epson.ssf": "ssf",
        "application/vnd.epson.quickanime": "qam",
        "application/vnd.intu.qfx": "qfx",
        "application/x-rar-compressed": "rar",
        "application/rsd+xml": "rsd",
        "application/vnd.realvnc.bed": "bed",
        "application/vnd.recordare.musicxml": "mxl",
        "application/vnd.recordare.musicxml+xml": "musicxml",
        "application/relax-ng-compact-syntax": "rnc",
        "application/vnd.data-vision.rdz": "rdz",
        "application/rdf+xml": "rdf",
        "application/vnd.cloanto.rp9": "rp9",
        "application/vnd.jisp": "jisp",
        "application/vnd.route66.link66+xml": "link66",
        "application/rss+xml": "xml",
        "application/shf+xml": "shf",
        "application/vnd.sailingtracker.track": "st",
        "application/vnd.sus-calendar": "sus",
        "application/sru+xml": "sru",
        "application/vnd.sema": "sema",
        "application/vnd.semd": "semd",
        "application/vnd.semf": "semf",
        "application/vnd.seemail": "see",
        "application/x-font-snf": "snf",
        "application/scvp-vp-request": "spq",
        "application/scvp-vp-response": "spp",
        "application/scvp-cv-request": "scq",
        "application/scvp-cv-response": "scs",
        "application/vnd.shana.informed.formdata": "ifm",
        "application/vnd.shana.informed.formtemplate": "itp",
        "application/vnd.shana.informed.interchange": "iif",
        "application/vnd.shana.informed.package": "ipk",
        "application/thraud+xml": "tfi",
        "application/vnd.epson.salt": "slt",
        "application/vnd.accpac.simply.aso": "aso",
        "application/vnd.accpac.simply.imp": "imp",
        "application/vnd.simtech-mindmapper": "twd",
        "application/vnd.commonspace": "csp",
        "application/vnd.yamaha.smaf-audio": "saf",
        "application/vnd.smaf": "mmf",
        "application/vnd.yamaha.smaf-phrase": "spf",
        "application/vnd.smart.teacher": "teacher",
        "application/vnd.svd": "svd",
        "application/sparql-query": "rq",
        "application/sparql-results+xml": "srx",
        "application/srgs": "gram",
        "application/srgs+xml": "grxml",
        "application/ssml+xml": "ssml",
        "application/vnd.koan": "skp",
        "application/vnd.stardivision.calc": "sdc",
        "application/vnd.stardivision.draw": "sda",
        "application/vnd.stardivision.impress": "sdd",
        "application/vnd.stardivision.math": "smf",
        "application/vnd.stardivision.writer": "sdw",
        "application/vnd.stardivision.writer-global": "sgl",
        "application/vnd.stepmania.stepchart": "sm",
        "application/x-stuffitx": "sitx",
        "application/vnd.solent.sdkm+xml": "sdkm",
        "application/vnd.olpc-sugar": "xo",
        "application/vnd.wqd": "wqd",
        "application/vnd.symbian.install": "sis",
        "application/smil+xml": "smi",
        "application/vnd.syncml+xml": "xsm",
        "application/vnd.syncml.dm+wbxml": "bdm",
        "application/vnd.syncml.dm+xml": "xdm",
        "application/sbml+xml": "sbml",
        "application/vnd.tao.intent-module-archive": "tao",
        "application/x-tex-tfm": "tfm",
        "application/tei+xml": "tei",
        "application/vnd.spotfire.dxp": "dxp",
        "application/vnd.spotfire.sfs": "sfs",
        "application/timestamped-data": "tsd",
        "application/vnd.trid.tpt": "tpt",
        "application/vnd.triscape.mxs": "mxs",
        "text/troff": "t",
        "application/vnd.trueapp": "tra",
        "application/x-font-ttf": "ttf",
        "text/turtle": "ttl",
        "application/vnd.umajin": "umj",
        "application/vnd.uoml+xml": "uoml",
        "application/vnd.unity": "unityweb",
        "application/vnd.ufdl": "ufd",
        "application/vnd.uiq.theme": "utz",
        "application/vnd.vsf": "vsf",
        "application/vnd.vcx": "vcx",
        "model/vnd.mts": "mts",
        "model/vnd.vtu": "vtu",
        "application/vnd.visionary": "vis",
        "application/ccxml+xml,": "ccxml",
        "application/voicexml+xml": "vxml",
        "application/vnd.wap.wbxml": "wbxml",
        "application/davmount+xml": "davmount",
        "application/x-font-woff": "woff",
        "application/wspolicy+xml": "wspolicy",
        "image/webp": "webp",
        "application/vnd.webturbo": "wtb",
        "application/widget": "wgt",
        "application/vnd.wordperfect": "wpd",
        "application/vnd.wt.stf": "stf",
        "application/wsdl+xml": "wsdl",
        "application/x-xfig": "fig",
        "application/xhtml+xml": "xhtml",
        "application/xcap-diff+xml": "xdf",
        "application/xenc+xml": "xenc",
        "application/patch-ops-error+xml": "xer",
        "application/resource-lists+xml": "rl",
        "application/rls-services+xml": "rs",
        "application/resource-lists-diff+xml": "rld",
        "application/xslt+xml": "xslt",
        "application/xop+xml": "xop",
        "application/x-xpinstall": "xpi",
        "application/xspf+xml": "xspf",
        "application/vnd.mozilla.xul+xml": "xul",
        "chemical/x-xyz": "xyz",
        "application/yang": "yang",
        "application/yin+xml": "yin",
        "application/vnd.zul": "zir",
        "application/vnd.handheld-entertainment+xml": "zmm",
        "application/vnd.zzazz.deck+xml": "zaz"
    };

}));